theme: PaperMod
baseURL: https://speeddragon.github.io/
languageCode: en-us
title: SpeedDragon Blog
module:
  mounts:
    - source: static
      target: static
    - source: images
      target: static/images
params:
  env: production
  keywords:
    - security
    - elixir
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  comments: true
  socialIcons:
  - name: "github"
    url: "https://github.com/speeddragon"
  - name: "x"
    url: "https://x.com/speeddragon"

  homeInfoParams:
    Title: "Welcome to my blog"
    Content: >
      Hi! I'm a software engineer with interest in distributed systems. I'm currently working with Elixir and Erlang. You will find content here mostly regarding Elixir and Security.
menu:
  main:
    - identifier: archives
      name: archives 
      url: /archives/
      weight: 8
    - identifier: search
      name: search 
      url: /search/
      weight: 9
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
services:
  googleAnalytics:
    ID: G-7KQHSZCH69
fuseOpts:
  isCaseSensitive: false
  shouldSort: true
  location: 0
  distance: 1000
  threshold: 0.4
  minMatchCharLength: 0
  limit: 10
  keys:
    - title
    - permalink
    - summary
    - content
markup:
  goldmark:
    duplicateResourceFiles: false
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      cjk:
        eastAsianLineBreaks: false
        eastAsianLineBreaksStyle: simple
        enable: false
        escapedSpace: false
      extras:
        delete:
          enable: false
        insert:
          enable: false
        mark:
          enable: false
        subscript:
          enable: false
        superscript:
          enable: false
      passthrough:
        enable: false
        delimiters:
          block: []
          inline: []
      typographer:
        apostrophe: "&rsquo;"
        disable: false
        ellipsis: "&hellip;"
        emDash: "&mdash;"
        enDash: "&ndash;"
        leftAngleQuote: "&laquo;"
        leftDoubleQuote: "&ldquo;"
        leftSingleQuote: "&lsquo;"
        rightAngleQuote: "&raquo;"
        rightDoubleQuote: "&rdquo;"
        rightSingleQuote: "&rsquo;"
    parser:
      autoDefinitionTermID: false
      autoHeadingID: true
      autoIDType: github
      wrapStandAloneImageWithinParagraph: true
      attribute:
        block: true
        title: true
    renderHooks:
      image:
        enableDefault: false
        useEmbedded: auto
      link:
        enableDefault: false
        useEmbedded: auto
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false

outputs:
  home:
    - HTML
    - RSS
    - JSON

